[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.20'
optimizer = true
optimizer_runs = 200

[profile.ci]
fuzz_runs = 10_000
forge_fuzz_runs = 10_000

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
basescan = { key = "${BASESCAN_API_KEY}" }